# Generated by Django 4.2.28 on 2026-02-08 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0002_rename_id_item_item_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='item_id',
            new_name='id',
        ),
    ]
