# Generated by Django 4.2.28 on 2026-02-08 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0003_rename_item_id_item_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='id',
            field=models.UUIDField(default='<function uuid4 at 0x110fc0670>', editable=False, primary_key=True, serialize=False),
        ),
    ]
