# Generated by Django 4.2.28 on 2026-02-11 18:01

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0005_alter_item_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='owner_id',
            field=models.CharField(default=uuid.uuid4, editable=False, max_length=64),
        ),
    ]
